language: node_js
node_js:
 - "node"
 - "lts/*"
before_install:
  - echo {\"token\":\"FAKE_TOKEN\"} > src/config.json
script:
 - npm run build
branches:
 only:
  - master
  - develop
notifications:
 email:
  on_success: never
  on_failure: always